packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

linkWorkspacePackages: true

packageManagerStrict: false

preferWorkspacePackages: true

saveWorkspaceProtocol: false

shamefullyHoist: true

strictPeerDependencies: true
